### ISSUE TITLE
Missing xlsx_list variable

### ISSUE THREAD

**Issue by kq-code** [docwalitt/National-Institutes-of-Health-Myalgic-Encephalomyelitis-Chronic-Fatigue-Syndrome-Code-Repository#1]
I'm trying to run the Nature Comms MECFS Re-Run Stats Script.R script based on the instructions in the readme but you make reference to a variable "xlsx_list" that is not established anywhere in the code. Can you add lines establishing this variable? The code seems to not work without it.

**Comment by srlamunion** [comment]
The READ.me and the [Nature Comms NINDS MECFS Figure Creation.R](https://github.com/docwalitt/National-Institutes-of-Health-Myalgic-Encephalomyelitis-Chronic-Fatigue-Syndrome-Code-Repository/blob/main/Nature%20Comms%20NINDS%20MECFS%20Figure%20Creation.R) file have been revised to make former references to 'xlsx_list' now refer to the 'source_data' object.
